name: docker-build-admin
on:
  workflow_dispatch:
#permissions:
#  contents: read
#  # Optional: allow read access to pull request. Use with `only-new-issues` option.
#  # pull-requests: read
jobs:
  docker-build:
    name: docker-build-admin-frontend
    runs-on: ubuntu-latest
    #needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Build Docker Image
        run: |
          echo "Version: $VERSION"
          echo "Additional Version: $ADDITIONAL_VERSION"
          make admin-container
        env:
          BUILD_TYPE: "production"
          ENV: "production"
      - name: Login To ECR
        run: make get-ecr-credentials
      - name: Push To ECR
        run: make docker-push-admin
